---
title: Leanontree
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    author: Punyasloka Parida
    title: Lean On Tree
source: "."
destination: "./_site"
name: Lean On Tree
description: Living, breathing, seeing, observing, existing. Sometimes, we all need
  to LeanOnTree.It's a story. It's life. Yours and mine.
highlighter: rouge
permalink: none
paginate: 5
url: https://leanontree.com
paginate_path: "/page:num/"
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
excerpt_separator: "<!--more-->"
exclude: [vendor, build_script,Gemfile,Gemfile.lock,tag/tag_template_generator.py]
plugins: 
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-octicons
analytics:
  provider: google
  google:
    tracking_id: UA-65359714-1
